import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{createClient,Session}from'@supabase/supabase-js';import'./styles.css';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;const db:any=createClient<any>(url,key);const scoped=(name:string):any=>createClient(url,key,{db:{schema:name} as any} as any) as any;const commerce:any=scoped('commerce'),inventory:any=scoped('inventory'),production:any=scoped('production'),analytics:any=scoped('analytics');const domainClients:any={catalog:scoped('catalog'),inventory,logistics:scoped('logistics'),platform:scoped('platform'),communication:scoped('communication'),cms:scoped('cms'),marketing:scoped('marketing'),identity:scoped('identity')};
const transitions:any={pending:['payment_pending','cancelled'],payment_pending:['paid','cancelled'],paid:['processing','cancelled'],processing:['shipped','cancelled'],shipped:['delivered','cancelled'],delivered:['returned']};
const prod:any={planned:['in_progress','cancelled'],in_progress:['completed','cancelled'],completed:['closed']};
const checks=[['products','catalog.products'],['variants','catalog.product_variants'],['prices','catalog.prices'],['locations','inventory.locations'],['inventory','inventory.items'],['carriers','logistics.carriers'],['shipping areas','logistics.shipping_areas'],['shipping methods','logistics.shipping_methods'],['shipping rules','logistics.shipping_rules'],['integrations','platform.integrations'],['message templates','communication.message_templates'],['homepage blocks','cms.homepage_blocks'],['campaigns','marketing.campaigns'],['feature flags','platform.feature_flags'],['platform settings','platform.platform_settings'],['staff roles','identity.user_roles']];
function App(){const[session,setSession]=useState<Session|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[tab,setTab]=useState('dashboard'),[e,setE]=useState(''),[orders,setOrders]=useState<any[]>([]),[stock,setStock]=useState<any[]>([]),[production,setProduction]=useState<any[]>([]),[kpi,setKpi]=useState<any>(null),[health,setHealth]=useState<any[]>([]),[catalogRows,setCatalogRows]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[shipping,setShipping]=useState<any>({carriers:[],areas:[],methods:[],rules:[]}),[campaigns,setCampaigns]=useState<any[]>([]),[finance,setFinance]=useState<any>({payments:[],settlements:[],reconciliations:[]}),[ai,setAi]=useState<any>({recommendations:[],actions:[]}),[busy,setBusy]=useState('');
useEffect(()=>{db.auth.getSession().then((x:any)=>setSession(x.data.session));const s=db.auth.onAuthStateChange((_:any,x:any)=>setSession(x));return()=>s.data.subscription.unsubscribe()},[]);
async function login(){const{error}=await db.auth.signInWithPassword({email,password});if(error)setE(error.message)}
async function load(){setE('');const[o,i,p,k]=await Promise.all([(commerce as any).from('orders').select('id,order_number,status,currency,grand_total,created_at').order('created_at',{ascending:false}).limit(50),(inventory as any).from('items').select('id,product_variant_id,on_hand,reserved,reorder_point').limit(50),(production as any).from('orders').select('id,order_number,status,planned_at,started_at,completed_at').order('planned_at',{ascending:false}).limit(30),(analytics as any).from('kpis_daily').select('*').order('day',{ascending:false}).limit(1).maybeSingle()]);const hs=await Promise.all(checks.map(async([label,path])=>{const[s,t]=path.split('.');const q=await domainClients[s].from(t).select('id',{count:'exact',head:true});return{label,path,count:q.count??0,error:q.error?.message||''}}));const[cus,shipC,shipA,shipM,shipR,camp,pay,sett,rec,recos,actions]=await Promise.all([(domainClients.customer||scoped('customer')).from('customers').select('id,public_id,first_name,last_name,email,phone,status,created_at').order('created_at',{ascending:false}).limit(50),domainClients.logistics.from('carriers').select('*').limit(50),domainClients.logistics.from('shipping_areas').select('*').limit(50),domainClients.logistics.from('shipping_methods').select('*').limit(50),domainClients.logistics.from('shipping_rules').select('*').limit(50),domainClients.marketing.from('campaigns').select('*').order('created_at',{ascending:false}).limit(50),scoped('finance').from('payments').select('*').order('created_at',{ascending:false}).limit(50),scoped('finance').from('settlements').select('*').order('created_at',{ascending:false}).limit(50),scoped('finance').from('reconciliations').select('*').order('created_at',{ascending:false}).limit(50),scoped('ai').from('recommendations').select('*').order('created_at',{ascending:false}).limit(50),scoped('ai').from('action_requests').select('*').order('created_at',{ascending:false}).limit(50)]);const bad=[o,i,p,k].find(x=>x.error);if(bad)setE(bad.error!.message);setOrders(o.data||[]);setStock(i.data||[]);setProduction(p.data||[]);setKpi(k.data);setHealth(hs);setCustomers(cus.data||[]);setShipping({carriers:shipC.data||[],areas:shipA.data||[],methods:shipM.data||[],rules:shipR.data||[]});setCampaigns(camp.data||[]);setFinance({payments:pay.data||[],settlements:sett.data||[],reconciliations:rec.data||[]});setAi({recommendations:recos.data||[],actions:actions.data||[]});const cp=await db.from('storefront_products').select('id,name_ar,name_en,slug,status,brand_name,created_at').order('created_at',{ascending:false}).limit(100);setCatalogRows(cp.data||[])}
useEffect(()=>{if(session)load()},[session]);
async function tr(id:string,s:string){setBusy(id+s);const{error}=await (commerce as any).rpc('transition_order',{p_order_id:id,p_to_status:s,p_reason:'admin'});if(error)setE(error.message);await load();setBusy('')}
async function pt(id:string,s:string){setBusy(id+s);const{error}=await (production as any).rpc('transition_order',{p_order_id:id,p_to_status:s,p_reason:'admin'});if(error)setE(error.message);await load();setBusy('')}
const blockers=useMemo(()=>health.filter(x=>['carriers','shipping areas','shipping methods','shipping rules','integrations','message templates','staff roles'].includes(x.label)&&x.count===0),[health]);
if(!session)return <main dir="rtl" className="auth"><h1>SIWA BUSINESS</h1><p>Business Console</p><input placeholder="البريد" value={email} onChange={x=>setEmail(x.target.value)}/><input type="password" placeholder="كلمة المرور" value={password} onChange={x=>setPassword(x.target.value)}/><button onClick={login}>دخول الإدارة</button>{e&&<div className="error">{e}</div>}</main>;
return <main dir="rtl"><header><div><span>SIWA BUSINESS CONSOLE</span><h1>مركز التحكم</h1><p>Commerce · Operations · Growth · Finance · Marketing · AI</p></div><div><button onClick={load}>تحديث</button> <button className="ghost" onClick={()=>db.auth.signOut()}>خروج</button></div></header><nav>{[['dashboard','الرئيسية'],['orders','الطلبات'],['inventory','المخزون'],['production','الإنتاج / QC'],['catalog','الكتالوج'],['customers','العملاء'],['shipping','الشحن'],['marketing','التسويق'],['finance','المالية'],['ai','AI'],['health','جاهزية التشغيل']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav>{e&&<div className="error">{e}</div>}
{tab==='dashboard'&&<><section className="stats"><div><b>{orders.length}</b><span>آخر الطلبات</span></div><div><b>{stock.length}</b><span>Inventory Items</span></div><div><b>{production.length}</b><span>Production</span></div><div><b>{kpi?.gross_sales??0}</b><span>Gross Sales</span></div></section><section className="panel"><h2>Production Readiness</h2><p>الـbackend domains متصلة مباشرة. العناصر التي تحتاج بيانات تشغيل حقيقية تظهر في جاهزية التشغيل.</p>{blockers.length?<div className="warning"><b>{blockers.length} عناصر تمنع التشغيل الكامل</b><ul>{blockers.map(x=><li key={x.path}>{x.label}: لا توجد بيانات</li>)}</ul></div>:<div className="ok">لا توجد blockers من قائمة التشغيل الأساسية.</div>}</section></>}
{tab==='orders'&&<section className="panel"><h2>الطلبات</h2>{orders.length?orders.map(o=><article className="row" key={o.id}><b>{o.order_number}</b><span>{o.status}</span><strong>{Number(o.grand_total).toFixed(2)} {o.currency}</strong><div>{(transitions[o.status]||[]).map((s:string)=><button key={s} disabled={!!busy} onClick={()=>tr(o.id,s)}>{busy===o.id+s?'...':s}</button>)}</div></article>):<p className="muted">لا توجد طلبات بعد.</p>}</section>}
{tab==='inventory'&&<section className="panel"><h2>المخزون</h2>{stock.length?stock.map(x=><article className="row" key={x.id}><b>{x.product_variant_id}</b><span>On hand {x.on_hand}</span><span>Reserved {x.reserved}</span><strong>Available {Number(x.on_hand)-Number(x.reserved)}</strong></article>):<p className="muted">لا توجد عناصر مخزون.</p>}</section>}
{tab==='production'&&<section className="panel"><h2>الإنتاج + QC</h2>{production.length?production.map(x=><article className="row" key={x.id}><b>{x.order_number}</b><span>{x.status}</span><div>{(prod[x.status]||[]).map((s:string)=><button key={s} disabled={!!busy} onClick={()=>pt(x.id,s)}>{s}</button>)}</div></article>):<p className="muted">لا توجد أوامر إنتاج.</p>}</section>}
{tab==='catalog'&&<section className="panel"><h2>Catalog</h2><p className="muted">قراءة الكتالوج من storefront views الآمنة. إدارة البيانات الكتابية ستُضاف بعد تثبيت صلاحيات staff المناسبة.</p>{catalogRows.length?catalogRows.map(x=><article className="row" key={x.id}><b>{x.name_ar}</b><span>{x.name_en||'—'}</span><span>{x.brand_name||'Siwa'}</span><strong>{x.status}</strong></article>):<p className="muted">لا توجد منتجات منشورة أو لا توجد صلاحية قراءة.</p>}</section>}
{tab==='customers'&&<section className="panel"><h2>Customer 360</h2>{customers.length?customers.map(x=><article className="row" key={x.id}><b>{x.public_id}</b><span>{[x.first_name,x.last_name].filter(Boolean).join(' ')||'—'}</span><span>{x.email||x.phone||'—'}</span><strong>{x.status}</strong></article>):<p className="muted">لا توجد بيانات عملاء أو الصلاحية غير متاحة.</p>}</section>}
{tab==='shipping'&&<section className="panel"><h2>Shipping Control</h2><div className="stats"><div><b>{shipping.carriers.length}</b><span>Carriers</span></div><div><b>{shipping.areas.length}</b><span>Areas</span></div><div><b>{shipping.methods.length}</b><span>Methods</span></div><div><b>{shipping.rules.length}</b><span>Rules</span></div></div>{shipping.rules.map((x:any)=><article className="row" key={x.id}><b>{x.name||x.code||x.id}</b><span>{x.status||'configured'}</span><strong>{x.price??x.amount??'—'}</strong></article>)}</section>}
{tab==='marketing'&&<section className="panel"><h2>Marketing & Attribution</h2>{campaigns.length?campaigns.map(x=><article className="row" key={x.id}><b>{x.name}</b><span>{x.code}</span><span>{x.status}</span><strong>{x.budget??'—'} {x.currency||''}</strong></article>):<p className="muted">لا توجد حملات أو الصلاحية غير متاحة.</p>}</section>}
{tab==='finance'&&<section className="panel"><h2>Finance</h2><div className="stats"><div><b>{finance.payments.length}</b><span>Payments</span></div><div><b>{finance.settlements.length}</b><span>Settlements</span></div><div><b>{finance.reconciliations.length}</b><span>Reconciliations</span></div></div>{finance.payments.slice(0,20).map((x:any)=><article className="row" key={x.id}><b>{x.provider_reference||x.id}</b><span>{x.status}</span><strong>{x.amount} {x.currency}</strong></article>)}</section>}
{tab==='ai'&&<section className="panel"><h2>AI Business Control</h2><div className="stats"><div><b>{ai.recommendations.length}</b><span>Recommendations</span></div><div><b>{ai.actions.length}</b><span>Action Requests</span></div></div>{ai.actions.map((x:any)=><article className="row" key={x.id}><b>{x.action_type}</b><span>{x.risk_level}</span><strong>{x.status}</strong></article>)}</section>}
{tab==='health'&&<section className="panel"><h2>جاهزية التشغيل</h2><div className="health">{health.map(x=><article key={x.path} className={x.error?'bad':x.count?'ready':'missing'}><b>{x.label}</b><span>{x.error?'خطأ صلاحيات/قراءة':x.count+' سجل'}</span><small>{x.path}</small></article>)}</div><p className="muted">الصفر هنا لا يعني أن الـschema ناقص؛ يعني فقط أن بيانات التشغيل غير مُدخلة.</p></section>}
</main>}
createRoot(document.getElementById('root')!).render(<App/>);