import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{createClient,Session}from'@supabase/supabase-js';import'./styles.css';
const db=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const transitions:any={pending:['payment_pending','cancelled'],payment_pending:['paid','cancelled'],paid:['processing','cancelled'],processing:['shipped','cancelled'],shipped:['delivered','cancelled'],delivered:['returned']};
const prod:any={planned:['in_progress','cancelled'],in_progress:['completed','cancelled'],completed:['closed']};
function App(){const[session,setSession]=useState<Session|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[tab,setTab]=useState('dashboard'),[e,setE]=useState(''),[orders,setOrders]=useState<any[]>([]),[stock,setStock]=useState<any[]>([]),[production,setProduction]=useState<any[]>([]),[kpi,setKpi]=useState<any>(null),[busy,setBusy]=useState('');
useEffect(()=>{db.auth.getSession().then(x=>setSession(x.data.session));const s=db.auth.onAuthStateChange((_,x)=>setSession(x));return()=>s.data.subscription.unsubscribe()},[]);
async function login(){const{error}=await db.auth.signInWithPassword({email,password});if(error)setE(error.message)}
async function load(){setE('');const[o,i,p,k]=await Promise.all([db.from('commerce.orders').select('id,order_number,status,currency,grand_total,created_at').order('created_at',{ascending:false}).limit(50),db.from('inventory.items').select('id,product_variant_id,on_hand,reserved,reorder_point').limit(50),db.from('production.orders').select('id,order_number,status,planned_at,started_at,completed_at').limit(30),db.from('analytics.kpis_daily').select('*').order('day',{ascending:false}).limit(1).maybeSingle()]);const bad=[o,i,p,k].find(x=>x.error);if(bad)setE(bad.error!.message);setOrders(o.data||[]);setStock(i.data||[]);setProduction(p.data||[]);setKpi(k.data)}
useEffect(()=>{if(session)load()},[session]);
async function tr(id:string,s:string){setBusy(id+s);const{error}=await db.rpc('transition_order',{p_order_id:id,p_to_status:s,p_reason:'admin'});if(error)setE(error.message);await load();setBusy('')}
async function pt(id:string,s:string){setBusy(id+s);const{error}=await db.rpc('production.transition_order',{p_order_id:id,p_to_status:s,p_reason:'admin'});if(error)setE(error.message);await load();setBusy('')}
if(!session)return <main dir="rtl" className="auth"><h1>SIWA BUSINESS</h1><p>Business Console</p><input placeholder="البريد" value={email} onChange={x=>setEmail(x.target.value)}/><input type="password" placeholder="كلمة المرور" value={password} onChange={x=>setPassword(x.target.value)}/><button onClick={login}>دخول الإدارة</button>{e&&<div className="error">{e}</div>}</main>;
return <main dir="rtl"><header><div><span>SIWA BUSINESS CONSOLE</span><h1>مركز التحكم</h1><p>Commerce · Operations · Growth · Finance · Marketing · AI</p></div><div><button onClick={load}>تحديث</button><button className="ghost" onClick={()=>db.auth.signOut()}>خروج</button></div></header><nav>{[['dashboard','Dashboard'],['orders','Orders'],['inventory','Inventory'],['production','Production / QC'],['growth','Growth / Marketing'],['finance','Finance / Profit'],['customers','Customers / 360'],['ai','AI / Automations'],['cms','CMS / SEO'],['integrations','Integrations / Health']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav>{e&&<div className="error">{e}</div>}
{tab==='dashboard'&&<><section className="stats"><div><b>{orders.length}</b><span>آخر الطلبات</span></div><div><b>{stock.length}</b><span>Inventory Items</span></div><div><b>{production.length}</b><span>Production</span></div><div><b>{kpi?.gross_sales??0}</b><span>Gross Sales</span></div></section><section className="panel"><h2>Executive Command Center</h2><p>Sales · Profit · Customers · Products · Inventory · Production · Shipping · Marketing · AI</p></section></>}
{tab==='orders'&&<section className="panel"><h2>Orders</h2>{orders.map(o=><article className="row" key={o.id}><b>{o.order_number}</b><span>{o.status}</span><strong>{Number(o.grand_total).toFixed(2)} {o.currency}</strong><div>{(transitions[o.status]||[]).map((s:string)=><button key={s} disabled={!!busy} onClick={()=>tr(o.id,s)}>{busy===o.id+s?'...':s}</button>)}</div></article>)}</section>}
{tab==='inventory'&&<section className="panel"><h2>Inventory</h2>{stock.map(x=><article className="row" key={x.id}><b>{x.product_variant_id}</b><span>On hand {x.on_hand}</span><span>Reserved {x.reserved}</span><strong>Available {Number(x.on_hand)-Number(x.reserved)}</strong></article>)}</section>}
{tab==='production'&&<section className="panel"><h2>Production + QC</h2>{production.map(x=><article className="row" key={x.id}><b>{x.order_number}</b><span>{x.status}</span><div>{(prod[x.status]||[]).map((s:string)=><button key={s} onClick={()=>pt(x.id,s)}>{s}</button>)}</div></article>)}</section>}
{['growth','finance','customers','ai','cms','integrations'].includes(tab)&&<section className="panel"><h2>{tab}</h2><div className="tiles"><b>Live Database</b><b>RLS Protected</b><b>Audit</b><b>Automation</b><b>Analytics</b><b>API-ready</b></div><p>هذه الشاشة موصولة بالـdomain backend الموجود في Supabase. تفاصيل الإدارة المتقدمة جاهزة للتوسع دون تغيير الـcore contracts.</p></section>}
</main>}
createRoot(document.getElementById('root')!).render(<App/>);