import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient,Session}from'@supabase/supabase-js';
import'./styles.css';
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
const db=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const CART='siwa-cart-v2',WISH='siwa-wishlist-v1';
const catalog=db.schema('catalog'),commerce=db.schema('commerce'),inventory=db.schema('inventory');
function App(){const[tab,setTab]=useState('home'),[products,setProducts]=useState<any[]>([]),[variants,setVariants]=useState<any[]>([]),[prices,setPrices]=useState<any[]>([]),[session,setSession]=useState<Session|null>(null),[cart,setCart]=useState<any[]>(()=>JSON.parse(localStorage.getItem(CART)||'[]')),[wish,setWish]=useState<string[]>(()=>JSON.parse(localStorage.getItem(WISH)||'[]')),[q,setQ]=useState(''),[results,setResults]=useState<any[]>([]),[detail,setDetail]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[address,setAddress]=useState<any>({recipient_name:'',phone:'',governorate:'',city:'',area:'',street:'',building:'',floor:'',apartment:''});
useEffect(()=>{db.auth.getSession().then(x=>setSession(x.data.session));const s=db.auth.onAuthStateChange((_,x)=>setSession(x));return()=>s.data.subscription.unsubscribe()},[]);
useEffect(()=>{localStorage.setItem(CART,JSON.stringify(cart));localStorage.setItem(WISH,JSON.stringify(wish))},[cart,wish]);
useEffect(()=>{(async()=>{const[p,v,pr]=await Promise.all([catalog.from('products').select('*').eq('status','active').order('created_at',{ascending:false}),catalog.from('product_variants').select('*').eq('status','active'),catalog.from('prices').select('product_variant_id,amount,currency').eq('currency','EGP').eq('is_active',true)]);setProducts(p.data||[]);setVariants(v.data||[]);setPrices(pr.data||[])})()},[]);
const byV=useMemo(()=>new Map(variants.map(v=>[v.id,v])),[variants]),byP=useMemo(()=>new Map(variants.map(v=>[v.product_id,v])),[variants]),byPrice=useMemo(()=>new Map(prices.map(p=>[p.product_variant_id,p])),[prices]);
const rows=cart.map(i=>({i,v:byV.get(i.variantId),p:products.find(p=>p.id===byV.get(i.variantId)?.product_id),pr:byPrice.get(i.variantId)})).filter(x=>x.v&&x.p&&x.pr),total=rows.reduce((n,x)=>n+Number(x.pr.amount)*x.i.quantity,0),count=cart.reduce((n,x)=>n+x.quantity,0);
const add=(pid:string)=>{const v=byP.get(pid);if(!v)return;setCart((c:any[])=>c.some(x=>x.variantId===v.id)?c.map(x=>x.variantId===v.id?{...x,quantity:x.quantity+1}:x):[...c,{variantId:v.id,quantity:1}]);setMsg('تمت الإضافة للسلة')};
const toggle=(id:string)=>setWish(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);
async function search(){const{data,error}=await catalog.rpc('search_products',{p_query:q,p_min_price:null,p_max_price:null,p_available_only:true,p_limit:30});if(error)setErr(error.message);else setResults(data||[])}
async function openProduct(slug:string){const{data,error}=await catalog.from('machine_commerce_feed').select('*').eq('slug',slug).maybeSingle();if(error)setErr(error.message);else setDetail(data)}
async function auth(mode:string){const r=mode==='in'?await db.auth.signInWithPassword({email,password}):await db.auth.signUp({email,password,options:{data:{display_name:name,phone}}});if(r.error)setErr(r.error.message);else setMsg('تم بنجاح')}
async function loadOrders(){if(!session)return;const{data,error}=await commerce.from('orders').select('id,order_number,status,currency,grand_total,created_at').order('created_at',{ascending:false}).limit(30);if(error)setErr(error.message);else setOrders(data||[])}
async function checkout(){if(!session){setTab('account');setErr('سجّل الدخول أولًا');return}if(!rows.length){setErr('السلة فارغة');return}if(!address.recipient_name||!address.phone||!address.governorate||!address.city||!address.street){setErr('أكمل العنوان');return}const{data:l}=await inventory.from('locations').select('id').eq('code','MAIN').eq('is_active',true).limit(1);if(!l?.[0]){setErr('لا يوجد موقع بيع نشط');return}const{data,error}=await db.functions.invoke('checkout',{body:{currency:'EGP',locationId:l[0].id,items:rows.map(x=>({product_variant_id:x.v.id,quantity:x.i.quantity})),shippingAddress:address,customerSnapshot:{email:session.user.email,name,phone}}});if(error||data?.code){setErr(error?.message||data?.message||data?.code);return}setCart([]);setMsg('تم إنشاء الطلب '+data.order_number);await loadOrders()}
async function cancel(id:string){const{error}=await db.rpc('cancel_order_if_eligible',{p_order_id:id,p_reason:'customer_request'});if(error)setErr(error.message);else{setMsg('تم طلب الإلغاء');loadOrders()}}
async function ret(id:string){const{error}=await db.rpc('request_return',{p_order_id:id,p_reason:'customer_request'});if(error)setErr(error.message);else setMsg('تم إنشاء طلب الإرجاع')}
const card=(p:any)=><article className="card"><button className="media" onClick={()=>openProduct(p.slug)}>SIWA</button><div className="split"><span>{p.brand_name||'Siwa'}</span><button className="ghost" onClick={()=>toggle(p.id)}>{wish.includes(p.id)?'♥':'♡'}</button></div><h3>{p.name_ar}</h3><p>{p.description_ar||'منتج من سيوة.'}</p><strong>{(()=>{const v=byP.get(p.id),pr=v&&byPrice.get(v.id);return pr?Number(pr.amount).toFixed(2)+' EGP':'غير متاح'})()}</strong><button onClick={()=>add(p.id)}>أضف للسلة</button></article>;
return <main dir="rtl"><header><div><span className="eyebrow">SIWA SMART COMMERCE</span><h1>من واحة سيوة إلى باب بيتك 🌿</h1><p>تجربة تجارة ذكية متصلة بالمخزون والطلب والمحتوى.</p></div><div className="top"><button onClick={()=>setTab('search')}>بحث</button><button onClick={()=>setTab('wishlist')}>المفضلة {wish.length}</button><button onClick={()=>setTab('account')}>{session?'حسابي':'دخول'}</button><button onClick={()=>setTab('cart')}>السلة {count}</button></div></header>
<nav><button onClick={()=>setTab('home')}>الرئيسية</button><button onClick={()=>setTab('search')}>المنتجات</button><button onClick={()=>setTab('wishlist')}>Wishlist</button><button onClick={()=>setTab('account')}>طلباتي / Loyalty</button><button onClick={()=>setTab('support')}>الدعم</button></nav>
{msg&&<div className="notice">{msg}</div>}{err&&<div className="error">{err}</div>}
{tab==='home'&&<><section className="hero"><span>SIWA ORIGIN</span><h2>منتجات حقيقية، مصدر وقصة وثقة.</h2><p>Story · Education · Reviews · Offers · Bundles · Recommendations</p><button onClick={()=>setTab('search')}>ابدأ التسوق</button></section><section className="grid">{products.map(card)}</section></>}
{tab==='search'&&<section className="panel"><h2>Search Engine</h2><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="عربي / English / Synonyms..." /><button onClick={search}>بحث</button></div><div className="grid">{results.length?results.map(x=><article className="card" key={x.variant_id}><small>{x.sku}</small><h3>{x.name_ar}</h3><p>{x.name_en||''}</p><strong>{Number(x.price).toFixed(2)} {x.currency}</strong><button onClick={()=>add(x.product_id)}>أضف للسلة</button></article>):products.map(card)}</div></section>}
{tab==='wishlist'&&<section className="panel"><h2>Wishlist</h2><p>Save · Share · Price Drop · Back in Stock</p><div className="grid">{products.filter(p=>wish.includes(p.id)).map(card)}</div></section>}
{tab==='cart'&&<section className="panel"><h2>Cart + Smart Checkout</h2>{rows.map(x=><div className="line" key={x.i.variantId}><span>{x.p.name_ar} × {x.i.quantity}</span><b>{(Number(x.pr.amount)*x.i.quantity).toFixed(2)} EGP</b></div>)}<div className="total">الإجمالي <b>{total.toFixed(2)} EGP</b></div>{rows.length>0&&<><p>Free Shipping Progress · Points · Bundle Saving · Cross Sell · Delivery Promise</p>{['recipient_name','phone','governorate','city','area','street','building','floor','apartment'].map(k=><input key={k} placeholder={k} value={address[k]} onChange={e=>setAddress((a:any)=>({...a,[k]:e.target.value}))}/>)}<button onClick={checkout}>تأكيد الطلب</button></>}</section>}
{tab==='account'&&<section className="panel"><h2>Customer Account</h2>{!session?<><input placeholder="الاسم" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="الهاتف" value={phone} onChange={e=>setPhone(e.target.value)}/><input placeholder="البريد" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/><div className="top"><button onClick={()=>auth('in')}>دخول</button><button onClick={()=>auth('up')}>إنشاء حساب</button></div></>:<><p>{session.user.email}</p><div className="tiles"><b>Orders</b><b>Track</b><b>Buy Again</b><b>Points</b><b>Wallet</b><b>Coupons</b><b>Reviews</b><b>Returns</b><b>Gift Orders</b><b>Subscriptions</b></div><button onClick={loadOrders}>تحميل الطلبات</button>{orders.map(o=><article className="order" key={o.id}><b>{o.order_number}</b><span>{o.status}</span><strong>{Number(o.grand_total).toFixed(2)} {o.currency}</strong><div className="top">{['pending','payment_pending'].includes(o.status)&&<button onClick={()=>cancel(o.id)}>إلغاء</button>}{o.status==='delivered'&&<button onClick={()=>ret(o.id)}>Return</button>}</div></article>)}<button onClick={()=>db.auth.signOut()}>خروج</button></>}</section>}
{tab==='support'&&<section className="panel"><h2>Customer Service</h2><div className="tiles"><b>Chat</b><b>WhatsApp</b><b>Phone</b><b>Email</b><b>Tickets</b><b>FAQ</b><b>Complaints</b></div><p>SLA + Escalation + Self Service</p></section>}
{detail&&<div className="overlay" onClick={()=>setDetail(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button onClick={()=>setDetail(null)}>إغلاق</button><h2>{detail.name_ar}</h2><strong>{detail.amount} {detail.currency}</strong><h3>Story / Origin</h3><p>{detail.story_ar||detail.origin_ar||'غير مضاف بعد'}</p><h3>Education</h3><p>{detail.how_to_use_ar||'بيانات الاستخدام غير مضافة بعد'}</p><h3>Storage / Packaging / Batch</h3><p>{detail.storage_ar||'بيانات التخزين غير مضافة بعد'}</p><button onClick={()=>{add(detail.product_id);setDetail(null)}}>أضف للسلة</button></aside></div>}
</main>}
createRoot(document.getElementById('root')!).render(<App/>);