import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient,Session}from'@supabase/supabase-js';
import'./styles.css';
const db=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
const CART_KEY='siwa-cart-v1';
type Product={id:string;slug:string;name_ar:string;description_ar:string|null;brand_name:string|null};
type Variant={id:string;product_id:string;sku:string;name_ar:string|null};
type Price={product_variant_id:string;amount:number;currency:string};
type CartItem={variantId:string;quantity:number};
function App(){
const[products,setProducts]=useState<Product[]>([]),[variants,setVariants]=useState<Variant[]>([]),[prices,setPrices]=useState<Price[]>([]);
const[session,setSession]=useState<Session|null>(null),[cart,setCart]=useState<CartItem[]>(()=>JSON.parse(localStorage.getItem(CART_KEY)||'[]'));
const[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authBusy,setAuthBusy]=useState(false);
const[name,setName]=useState(''),[phone,setPhone]=useState('');
const[address,setAddress]=useState({recipient_name:'',phone:'',governorate:'',city:'',area:'',street:'',building:'',floor:'',apartment:''});
const[checkoutBusy,setCheckoutBusy]=useState(false),[lastOrder,setLastOrder]=useState<any>(null),[showCart,setShowCart]=useState(false),[showAuth,setShowAuth]=useState(false);
useEffect(()=>{db.auth.getSession().then(({data})=>setSession(data.session));const sub=db.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub.data.subscription.unsubscribe()},[]);
useEffect(()=>{(async()=>{setLoading(true);const[p,v,l]=await Promise.all([db.from('catalog.products').select('id,slug,name_ar,description_ar,brand_name').eq('status','active').order('created_at',{ascending:false}),db.from('catalog.product_variants').select('id,product_id,sku,name_ar').eq('status','active'),db.from('catalog.prices').select('product_variant_id,amount,currency').eq('currency','EGP').eq('is_active',true)]);const bad=[p,v,l].find(x=>x.error);if(bad)setError(bad.error!.message);setProducts(p.data||[]);setVariants(v.data||[]);setPrices(l.data||[]);setLoading(false)})()},[]);
useEffect(()=>localStorage.setItem(CART_KEY,JSON.stringify(cart)),[cart]);
const variantByProduct=useMemo(()=>new Map(variants.map(v=>[v.product_id,v])),[variants]);
const priceByVariant=useMemo(()=>new Map(prices.map(p=>[p.product_variant_id,p])),[prices]);
const cartDetails=useMemo(()=>cart.map(i=>{const v=variants.find(x=>x.id===i.variantId);const p=products.find(x=>x.id===v?.product_id);const price=priceByVariant.get(i.variantId);return{...i,v,p,price}}).filter(x=>x.v&&x.p&&x.price),[cart,variants,products,priceByVariant]);
const total=cartDetails.reduce((s,x)=>s+x.price.amount*x.quantity,0);const count=cart.reduce((s,x)=>s+x.quantity,0);
function add(productId:string){const v=variantByProduct.get(productId);if(!v){setError('المنتج غير متاح للبيع حاليًا');return}setCart(c=>{const old=c.find(x=>x.variantId===v.id);return old?c.map(x=>x.variantId===v.id?{...x,quantity:x.quantity+1}:x):[...c,{variantId:v.id,quantity:1}]});setMessage('تمت إضافة المنتج للسلة');setShowCart(true)}
function change(id:string,q:number){setCart(c=>q<1?c.filter(x=>x.variantId!==id):c.map(x=>x.variantId===id?{...x,quantity:q}:x))}
async function signIn(){setAuthBusy(true);setError('');const{error}=await db.auth.signInWithPassword({email,password});if(error)setError(error.message);else setMessage('تم تسجيل الدخول');setAuthBusy(false)}
async function signUp(){setAuthBusy(true);setError('');const{data,error}=await db.auth.signUp({email,password,options:{data:{display_name:name,phone}}});if(error)setError(error.message);else setMessage(data.session?'تم إنشاء الحساب':'تم إنشاء الحساب. راجع بريدك لتأكيده إذا كان التأكيد مفعّلًا.');setAuthBusy(false)}
async function checkout(){if(!session){setShowAuth(true);setError('سجّل الدخول أولًا لإتمام الطلب');return}if(!cartDetails.length){setError('السلة فارغة');return}if(!address.recipient_name||!address.phone||!address.governorate||!address.city||!address.street){setError('أكمل بيانات عنوان التوصيل');return}setCheckoutBusy(true);setError('');setMessage('');const{data:locs,error:le}=await db.from('inventory.locations').select('id').eq('code','MAIN').eq('is_active',true).limit(1);if(le||!locs?.[0]){setError(le?.message||'لا يوجد مخزن بيع نشط');setCheckoutBusy(false);return}const{data,error}=await db.functions.invoke('checkout',{body:{currency:'EGP',locationId:locs[0].id,items:cartDetails.map(x=>({product_variant_id:x.variantId,quantity:x.quantity})),shippingAddress:address,customerSnapshot:{email:session.user.email,name,phone}}});if(error){setError(error.message);setCheckoutBusy(false);return}if(data?.code){setError(data.message||data.code);setCheckoutBusy(false);return}setLastOrder(data);setCart([]);setShowCart(false);setMessage('تم إنشاء طلبك وحجز الكمية بنجاح');setCheckoutBusy(false)}
return <div className="page" dir="rtl">
<header><div><span className="eyebrow">SIWA SMART COMMERCE</span><h1>منتجات سيوة، بشكل أذكى.</h1><p>كتالوج حي متصل بالمخزون والتسعير والطلبات.</p></div><div className="actions"><button className="ghost" onClick={()=>setShowAuth(true)}>{session?'حسابي':'دخول / إنشاء حساب'}</button><button onClick={()=>setShowCart(true)}>السلة · {count}</button></div></header>
<section className="hero"><div><span>من سيوة إلى بابك</span><h2>منتجات حقيقية، وسلة وCheckout حقيقي.</h2><p>السعر يُعاد التحقق منه على الخادم، والكمية تُحجز ذريًا عند إنشاء الطلب.</p></div></section>
{message&&<div className="notice">{message}</div>}{error&&<div className="error">{error}</div>}
{lastOrder&&<section className="order-success"><b>طلبك اتعمل: {lastOrder.order_number}</b><span>الإجمالي: {Number(lastOrder.grand_total).toFixed(2)} EGP</span><small>الحالة: {lastOrder.status}</small></section>}
{loading?<div className="loading">جاري تحميل المنتجات...</div>:<section className="grid">{products.map(x=>{const v=variantByProduct.get(x.id);const price=v?priceByVariant.get(v.id):undefined;return <article key={x.id}><div className="media">SIWA</div><span className="tag">{x.brand_name||'Siwa'}</span><h3>{x.name_ar}</h3><p>{x.description_ar||'منتج من مجموعة سيوة.'}</p><strong>{price?Number(price.amount).toFixed(2)+' EGP':'السعر غير متاح'}</strong><button className="add" disabled={!price} onClick={()=>add(x.id)}>أضف للسلة</button></article>})}</section>}
{showCart&&<div className="overlay" onClick={()=>setShowCart(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>السلة</h2><button className="ghost" onClick={()=>setShowCart(false)}>إغلاق</button></div>{!cartDetails.length?<p>السلة فاضية.</p>:cartDetails.map(x=><div className="cart-row" key={x.variantId}><div><b>{x.p.name_ar}</b><small>{x.v.sku}</small></div><div><button onClick={()=>change(x.variantId,x.quantity-1)}>−</button><span>{x.quantity}</span><button onClick={()=>change(x.variantId,x.quantity+1)}>+</button></div><strong>{(x.price.amount*x.quantity).toFixed(2)}</strong></div>)}{cartDetails.length>0&&<><div className="total"><span>الإجمالي</span><b>{total.toFixed(2)} EGP</b></div>{session?<div className="checkout"><h3>بيانات التوصيل</h3>{['recipient_name','phone','governorate','city','area','street','building','floor','apartment'].map(k=><input key={k} placeholder={({recipient_name:'اسم المستلم',phone:'رقم الهاتف',governorate:'المحافظة',city:'المدينة',area:'المنطقة',street:'الشارع',building:'رقم المبنى',floor:'الدور',apartment:'الشقة'} as any)[k]} value={(address as any)[k]} onChange={e=>setAddress(a=>({...a,[k]:e.target.value}))}/>)}</div>:<button className="wide" onClick={()=>setShowAuth(true)}>سجّل الدخول لإتمام الطلب</button>}<button className="checkout-btn" disabled={checkoutBusy} onClick={checkout}>{checkoutBusy?'جاري إنشاء الطلب...':'تأكيد الطلب · '+total.toFixed(2)+' EGP'}</button></>}</aside></div>}
{showAuth&&<div className="overlay" onClick={()=>setShowAuth(false)}><aside className="auth" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>{session?'الحساب':'دخول / إنشاء حساب'}</h2><button className="ghost" onClick={()=>setShowAuth(false)}>إغلاق</button></div>{session?<><p>أنت مسجل الدخول بـ {session.user.email}</p><button className="wide" onClick={()=>db.auth.signOut()}>تسجيل الخروج</button></>:<><input placeholder="الاسم" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="الهاتف" value={phone} onChange={e=>setPhone(e.target.value)}/><input placeholder="البريد الإلكتروني" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="كلمة المرور" value={password} onChange={e=>setPassword(e.target.value)}/><div className="auth-actions"><button onClick={signIn} disabled={authBusy}>دخول</button><button className="ghost" onClick={signUp} disabled={authBusy}>إنشاء حساب</button></div></>}</aside></div>}
</div>}
}
createRoot(document.getElementById('root')!).render(<App/>);