create table inventory.locations (id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, location_type text not null default 'warehouse', is_active boolean not null default true, created_at timestamptz not null default now());
create table inventory.items (id uuid primary key default gen_random_uuid(), product_variant_id uuid not null references catalog.product_variants(id), location_id uuid not null references inventory.locations(id), on_hand numeric(18,3) not null default 0, reserved numeric(18,3) not null default 0, damaged numeric(18,3) not null default 0, quarantine numeric(18,3) not null default 0, reorder_point numeric(18,3) not null default 0, updated_at timestamptz not null default now(), unique(product_variant_id,location_id), check(on_hand>=0), check(reserved>=0));
create table inventory.reservations (id uuid primary key default gen_random_uuid(), product_variant_id uuid not null references catalog.product_variants(id), location_id uuid not null references inventory.locations(id), order_id uuid, quantity numeric(18,3) not null check(quantity>0), status text not null default 'pending', expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table inventory.transactions (id uuid primary key default gen_random_uuid(), product_variant_id uuid not null references catalog.product_variants(id), location_id uuid not null references inventory.locations(id), transaction_type text not null, quantity numeric(18,3) not null, reference_type text, reference_id uuid, batch_id uuid, created_by uuid references identity.user_profiles(id), created_at timestamptz not null default now());
create table production.batches (id uuid primary key default gen_random_uuid(), batch_code text unique not null, status text not null default 'planned', produced_at timestamptz, expires_at timestamptz, notes text, created_at timestamptz not null default now());
create table production.orders (id uuid primary key default gen_random_uuid(), order_number text unique not null, status text not null default 'planned', notes text, planned_at timestamptz, started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now());
create table production.items (id uuid primary key default gen_random_uuid(), production_order_id uuid not null references production.orders(id) on delete cascade, product_variant_id uuid not null references catalog.product_variants(id), quantity numeric(18,3) not null check(quantity>0), batch_id uuid references production.batches(id), created_at timestamptz not null default now());
create table production.qc_inspections (id uuid primary key default gen_random_uuid(), batch_id uuid not null references production.batches(id), status text not null default 'pending', inspector_id uuid references identity.user_profiles(id), inspected_at timestamptz, notes text, created_at timestamptz not null default now());
alter table inventory.locations enable row level security;
alter table inventory.items enable row level security;
alter table inventory.reservations enable row level security;
alter table inventory.transactions enable row level security;
alter table production.batches enable row level security;
alter table production.orders enable row level security;
alter table production.items enable row level security;
alter table production.qc_inspections enable row level security;
create policy locations_read on inventory.locations for select to authenticated using(platform.has_permission(auth.uid(),'inventory.read'));
create policy inventory_read on inventory.items for select to authenticated using(platform.has_permission(auth.uid(),'inventory.read'));
create policy reservations_read on inventory.reservations for select to authenticated using(platform.has_permission(auth.uid(),'inventory.read'));
create policy transactions_read on inventory.transactions for select to authenticated using(platform.has_permission(auth.uid(),'inventory.read'));
create policy production_read on production.orders for select to authenticated using(platform.has_permission(auth.uid(),'production.read'));
create policy batches_read on production.batches for select to authenticated using(platform.has_permission(auth.uid(),'production.read'));
create policy production_items_read on production.items for select to authenticated using(platform.has_permission(auth.uid(),'production.read'));
create policy qc_read on production.qc_inspections for select to authenticated using(platform.has_permission(auth.uid(),'qc.read'));