create table commerce.carts (id uuid primary key default gen_random_uuid(), customer_id uuid references customer.customers(id) on delete cascade, session_key text unique, currency text not null, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table commerce.cart_items (id uuid primary key default gen_random_uuid(), cart_id uuid not null references commerce.carts(id) on delete cascade, product_variant_id uuid not null references catalog.product_variants(id), quantity numeric(18,3) not null check(quantity>0), created_at timestamptz not null default now(), unique(cart_id,product_variant_id));
create table commerce.orders (id uuid primary key default gen_random_uuid(), order_number text unique not null, customer_id uuid not null references customer.customers(id), status text not null default 'pending', currency text not null, subtotal numeric(18,2) not null default 0, discount_total numeric(18,2) not null default 0, shipping_total numeric(18,2) not null default 0, tax_total numeric(18,2) not null default 0, grand_total numeric(18,2) not null default 0, customer_snapshot jsonb not null default '{}', shipping_address_snapshot jsonb not null default '{}', pricing_snapshot jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table commerce.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references commerce.orders(id) on delete cascade, product_id uuid not null references catalog.products(id), product_variant_id uuid not null references catalog.product_variants(id), sku_snapshot text, product_name_ar_snapshot text, product_name_en_snapshot text, quantity numeric(18,3) not null check(quantity>0), unit_price numeric(18,2) not null, line_total numeric(18,2) not null, created_at timestamptz not null default now());
create table commerce.order_status_history (id uuid primary key default gen_random_uuid(), order_id uuid not null references commerce.orders(id) on delete cascade, from_status text, to_status text not null, actor_id uuid references identity.user_profiles(id), reason text, created_at timestamptz not null default now());
create table commerce.payment_intents (id uuid primary key default gen_random_uuid(), order_id uuid not null references commerce.orders(id) on delete cascade, provider text not null, provider_reference text, amount numeric(18,2) not null, currency text not null, status text not null default 'created', idempotency_key text unique, raw_response jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table commerce.order_addresses (id uuid primary key default gen_random_uuid(), order_id uuid not null references commerce.orders(id) on delete cascade, address_type text not null, snapshot jsonb not null, created_at timestamptz not null default now());
create or replace function commerce.resolve_active_price(p_variant uuid,p_currency text)
returns table(price_id uuid,amount numeric,currency text) language sql stable as $$
select id,amount,currency from catalog.prices where product_variant_id=p_variant and currency=p_currency and is_active and valid_from<=now() and (valid_to is null or valid_to>now()) order by priority desc,valid_from desc,created_at desc limit 1;
$$;
alter table commerce.carts enable row level security;
alter table commerce.cart_items enable row level security;
alter table commerce.orders enable row level security;
alter table commerce.order_items enable row level security;
alter table commerce.order_status_history enable row level security;
alter table commerce.payment_intents enable row level security;
alter table commerce.order_addresses enable row level security;
create policy carts_self on commerce.carts for all to authenticated using(customer_id=(select c.id from customer.customers c where c.auth_user_id=auth.uid())) with check(customer_id=(select c.id from customer.customers c where c.auth_user_id=auth.uid()));
create policy cart_items_self on commerce.cart_items for all to authenticated using(cart_id in (select id from commerce.carts where customer_id=(select c.id from customer.customers c where c.auth_user_id=auth.uid()))) with check(cart_id in (select id from commerce.carts where customer_id=(select c.id from customer.customers c where c.auth_user_id=auth.uid())));
create policy orders_self on commerce.orders for select to authenticated using(customer_id=(select c.id from customer.customers c where c.auth_user_id=auth.uid()) or platform.has_permission(auth.uid(),'orders.read'));
create policy order_items_self on commerce.order_items for select to authenticated using(order_id in (select id from commerce.orders where customer_id=(select c.id from customer.customers c where c.auth_user_id=auth.uid())) or platform.has_permission(auth.uid(),'orders.read'));
create policy payment_intents_self on commerce.payment_intents for select to authenticated using(order_id in (select id from commerce.orders where customer_id=(select c.id from customer.customers c where c.auth_user_id=auth.uid())) or platform.has_permission(auth.uid(),'payments.read'));
