-- 0018_operations_lifecycle.sql
insert into identity.roles(code,name,description,is_system) values
('super_admin','Super Admin','System-wide administration',true),('manager','Manager','Operational management',true),('workshop','Workshop','Production operations',true),('qc','QC','Quality control operations',true),('inventory','Inventory','Inventory operations',true),('shipping','Shipping','Shipping operations',true),('finance','Finance','Finance operations',true),('customer_service','Customer Service','Customer support operations',true) on conflict(code) do nothing;
insert into identity.permissions(code,name,description) values
('orders.read','Read Orders','View orders'),('orders.manage','Manage Orders','Manage order lifecycle'),('payments.manage','Manage Payments','Manage payment lifecycle'),('inventory.read','Read Inventory','View inventory'),('inventory.manage','Manage Inventory','Manage inventory operations'),('production.read','Read Production','View production'),('production.manage','Manage Production','Manage production lifecycle'),('qc.read','Read QC','View quality control'),('qc.manage','Manage QC','Manage quality control'),('shipping.read','Read Shipping','View shipping'),('shipping.manage','Manage Shipping','Manage shipping lifecycle'),('finance.read','Read Finance','View finance'),('finance.manage','Manage Finance','Manage finance operations') on conflict(code) do nothing;
insert into identity.role_permissions(role_id,permission_id) select r.id,p.id from identity.roles r cross join identity.permissions p where r.code='super_admin' on conflict do nothing;
insert into identity.role_permissions(role_id,permission_id) select r.id,p.id from identity.roles r join identity.permissions p on (r.code='manager' and p.code in ('orders.read','orders.manage','inventory.read','inventory.manage','production.read','production.manage','qc.read','qc.manage','shipping.read','shipping.manage','finance.read')) or (r.code='workshop' and p.code in ('production.read','production.manage','inventory.read')) or (r.code='qc' and p.code in ('production.read','qc.read','qc.manage')) or (r.code='inventory' and p.code in ('inventory.read','inventory.manage','production.read')) or (r.code='shipping' and p.code in ('orders.read','shipping.read','shipping.manage')) or (r.code='finance' and p.code in ('orders.read','finance.read','finance.manage')) or (r.code='customer_service' and p.code in ('orders.read')) on conflict do nothing;
create or replace function production.transition_order(p_order_id uuid,p_to_status text,p_reason text default null) returns production.orders language plpgsql security definer set search_path=production,platform,public as $$ declare v production.orders; v_from text; begin if auth.uid() is null or not platform.has_permission(auth.uid(),'production.manage') then raise exception 'FORBIDDEN'; end if; select * into v from production.orders where id=p_order_id for update; if not found then raise exception 'PRODUCTION_ORDER_NOT_FOUND'; end if; v_from:=v.status; if v_from=p_to_status then return v; end if; if not ((v_from='planned' and p_to_status in ('in_progress','cancelled')) or (v_from='in_progress' and p_to_status in ('completed','cancelled')) or (v_from='completed' and p_to_status='closed')) then raise exception 'INVALID_PRODUCTION_TRANSITION:%:%',v_from,p_to_status; end if; update production.orders set status=p_to_status,started_at=case when p_to_status='in_progress' then coalesce(started_at,now()) else started_at end,completed_at=case when p_to_status='completed' then coalesce(completed_at,now()) else completed_at end where id=p_order_id returning * into v; perform platform.record_event('production.order.transitioned','production_order',p_order_id,auth.uid(),jsonb_build_object('from',v_from,'to',p_to_status,'reason',p_reason),1); return v; end; $$;
revoke all on function production.transition_order(uuid,text,text) from public; grant execute on function production.transition_order(uuid,text,text) to authenticated;
create or replace function production.create_batch(p_batch_code text,p_produced_at timestamptz default null,p_expires_at timestamptz default null,p_notes text default null) returns production.batches language plpgsql security definer set search_path=production,platform,public as $$ declare v production.batches; begin if auth.uid() is null or not platform.has_permission(auth.uid(),'production.manage') then raise exception 'FORBIDDEN'; end if; if nullif(trim(p_batch_code),'') is null then raise exception 'INVALID_BATCH_CODE'; end if; insert into production.batches(batch_code,status,produced_at,expires_at,notes) values(trim(p_batch_code),'produced',p_produced_at,p_expires_at,p_notes) returning * into v; perform platform.record_event('production.batch.created','production_batch',v.id,auth.uid(),jsonb_build_object('batch_code',v.batch_code),1); return v; end; $$;
revoke all on function production.create_batch(text,timestamptz,timestamptz,text) from public; grant execute on function production.create_batch(text,timestamptz,timestamptz,text) to authenticated;
create or replace function production.record_qc(p_batch_id uuid,p_status text,p_notes text default null) returns production.qc_inspections language plpgsql security definer set search_path=production,platform,public as $$ declare v production.qc_inspections; begin if auth.uid() is null or not platform.has_permission(auth.uid(),'qc.manage') then raise exception 'FORBIDDEN'; end if; if p_status not in ('pending','passed','failed','rework') then raise exception 'INVALID_QC_STATUS'; end if; if not exists(select 1 from production.batches where id=p_batch_id) then raise exception 'BATCH_NOT_FOUND'; end if; insert into production.qc_inspections(batch_id,status,inspector_id,inspected_at,notes) values(p_batch_id,p_status,auth.uid(),now(),p_notes) returning * into v; update production.batches set status=case when p_status='passed' then 'approved' when p_status='failed' then 'rejected' when p_status='rework' then 'rework' else status end where id=p_batch_id; perform platform.record_event('production.qc.recorded','qc_inspection',v.id,auth.uid(),jsonb_build_object('batch_id',p_batch_id,'status',p_status),1); return v; end; $$;
revoke all on function production.record_qc(uuid,text,text) from public; grant execute on function production.record_qc(uuid,text,text) to authenticated;