-- 0028_gap_closure_consolidated.sql
-- Canonical replay for fresh environments. Live objects are created by 0024-0029.
create schema if not exists cms;
create schema if not exists communication;

create table if not exists customer.segments(id uuid primary key default gen_random_uuid(),code text unique not null,name_ar text not null,name_en text,conditions jsonb not null default '{}',status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists customer.segment_members(segment_id uuid not null references customer.segments(id) on delete cascade,customer_id uuid not null references customer.customers(id) on delete cascade,source text not null default 'rule',joined_at timestamptz not null default now(),primary key(segment_id,customer_id));
create table if not exists customer.wallets(customer_id uuid primary key references customer.customers(id) on delete cascade,balance numeric(18,2) not null default 0 check(balance>=0),currency text not null default 'EGP',updated_at timestamptz not null default now());
create table if not exists customer.wallet_transactions(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customer.customers(id),type text not null,amount numeric(18,2) not null,reference_type text,reference_id uuid,reason text,created_at timestamptz not null default now());

create table if not exists commerce.coupons(id uuid primary key default gen_random_uuid(),code text unique not null,discount_type text not null check(discount_type in ('fixed','percent')),discount_value numeric(18,4) not null check(discount_value>=0),min_subtotal numeric(18,2),max_discount numeric(18,2),usage_limit integer,per_customer_limit integer,starts_at timestamptz,ends_at timestamptz,status text not null default 'draft',rules jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists commerce.coupon_redemptions(id uuid primary key default gen_random_uuid(),coupon_id uuid not null references commerce.coupons(id),customer_id uuid references customer.customers(id),order_id uuid references commerce.orders(id),discount_amount numeric(18,2) not null default 0,created_at timestamptz not null default now());
create table if not exists commerce.offers(id uuid primary key default gen_random_uuid(),code text unique,name_ar text not null,name_en text,status text not null default 'draft',offer_type text not null,rules jsonb not null default '{}',starts_at timestamptz,ends_at timestamptz,priority integer not null default 0,created_at timestamptz not null default now());
create table if not exists commerce.offer_redemptions(id uuid primary key default gen_random_uuid(),offer_id uuid not null references commerce.offers(id),order_id uuid references commerce.orders(id),customer_id uuid references customer.customers(id),benefit jsonb not null default '{}',created_at timestamptz not null default now());

create table if not exists logistics.shipping_rules(id uuid primary key default gen_random_uuid(),code text unique not null,name_ar text not null,name_en text,status text not null default 'draft',conditions jsonb not null default '{}',price numeric(18,2) not null default 0,currency text not null default 'EGP',min_order numeric(18,2),max_order numeric(18,2),eta_min_days integer,eta_max_days integer,free_shipping_threshold numeric(18,2),priority integer not null default 0,created_at timestamptz not null default now());
create table if not exists logistics.delivery_promises(id uuid primary key default gen_random_uuid(),order_id uuid references commerce.orders(id) on delete cascade,location_id uuid references inventory.locations(id),carrier_id uuid references logistics.carriers(id),promised_from timestamptz,promised_to timestamptz,calculation jsonb not null default '{}',status text not null default 'calculated',created_at timestamptz not null default now());
create table if not exists logistics.shipping_areas(id uuid primary key default gen_random_uuid(),governorate text not null,area text not null,postal_code text,status text not null default 'active',unique(governorate,area));
create table if not exists logistics.shipping_methods(id uuid primary key default gen_random_uuid(),code text unique not null,name_ar text not null,name_en text,status text not null default 'active',config jsonb not null default '{}');
create table if not exists logistics.shipping_rule_methods(rule_id uuid not null references logistics.shipping_rules(id) on delete cascade,method_id uuid not null references logistics.shipping_methods(id) on delete cascade,primary key(rule_id,method_id));

create table if not exists marketing.ad_sets(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references marketing.campaigns(id) on delete cascade,name text not null,status text not null default 'draft',targeting jsonb not null default '{}',budget numeric(18,2),created_at timestamptz not null default now());
create table if not exists marketing.creatives(id uuid primary key default gen_random_uuid(),ad_set_id uuid references marketing.ad_sets(id) on delete cascade,name text not null,status text not null default 'draft',asset jsonb not null default '{}',copy_ar text,copy_en text,created_at timestamptz not null default now());
create table if not exists marketing.landing_pages(id uuid primary key default gen_random_uuid(),slug text unique not null,title_ar text not null,title_en text,status text not null default 'draft',blocks jsonb not null default '[]',seo jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists marketing.tracking_events(id uuid primary key default gen_random_uuid(),customer_id uuid references customer.customers(id),session_key text,event_name text not null,entity_type text,entity_id uuid,source text,medium text,campaign text,creative text,payload jsonb not null default '{}',occurred_at timestamptz not null default now());

create table if not exists cms.pages(id uuid primary key default gen_random_uuid(),slug text unique not null,title_ar text not null,title_en text,status text not null default 'draft',blocks jsonb not null default '[]',seo jsonb not null default '{}',published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists cms.blog_posts(id uuid primary key default gen_random_uuid(),slug text unique not null,title_ar text not null,title_en text,excerpt_ar text,excerpt_en text,body_ar text,body_en text,status text not null default 'draft',seo jsonb not null default '{}',published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists cms.homepage_blocks(id uuid primary key default gen_random_uuid(),code text unique not null,block_type text not null,config jsonb not null default '{}',status text not null default 'draft',sort_order integer not null default 0,starts_at timestamptz,ends_at timestamptz,targeting jsonb not null default '{}');

create table if not exists communication.message_templates(id uuid primary key default gen_random_uuid(),code text unique not null,channel text not null,language text not null default 'ar',version integer not null default 1,subject text,body text not null,variables jsonb not null default '[]',status text not null default 'draft',consent_required boolean not null default true,created_at timestamptz not null default now());
create table if not exists communication.message_logs(id uuid primary key default gen_random_uuid(),template_id uuid references communication.message_templates(id),customer_id uuid references customer.customers(id),channel text not null,recipient text,status text not null default 'queued',provider text,provider_reference text,payload jsonb not null default '{}',error_message text,sent_at timestamptz,created_at timestamptz not null default now());
create table if not exists communication.support_tickets(id uuid primary key default gen_random_uuid(),customer_id uuid references customer.customers(id),order_id uuid references commerce.orders(id),subject text not null,status text not null default 'open',priority text not null default 'normal',channel text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists communication.support_messages(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references communication.support_tickets(id) on delete cascade,sender_customer_id uuid references customer.customers(id),sender_staff_id uuid,body text not null,attachments jsonb not null default '[]',created_at timestamptz not null default now());

create table if not exists platform.business_rules(id uuid primary key default gen_random_uuid(),code text unique not null,name_ar text not null,name_en text,status text not null default 'draft',trigger_event text not null,conditions jsonb not null default '[]',actions jsonb not null default '[]',priority integer not null default 0,max_executions integer,created_at timestamptz not null default now());
create table if not exists platform.automations(id uuid primary key default gen_random_uuid(),code text unique not null,name_ar text not null,name_en text,status text not null default 'draft',trigger jsonb not null default '{}',steps jsonb not null default '[]',loop_guard jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists platform.automation_runs(id uuid primary key default gen_random_uuid(),automation_id uuid not null references platform.automations(id),event_id uuid,status text not null default 'queued',current_step integer not null default 0,context jsonb not null default '{}',scheduled_at timestamptz,started_at timestamptz,completed_at timestamptz,error_message text,attempts integer not null default 0,created_at timestamptz not null default now());
create table if not exists platform.risk_events(id uuid primary key default gen_random_uuid(),customer_id uuid references customer.customers(id),order_id uuid references commerce.orders(id),risk_type text not null,score numeric,decision text,signals jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists platform.integrations(id uuid primary key default gen_random_uuid(),code text unique not null,integration_type text not null,provider text,status text not null default 'disabled',config_public jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table if not exists finance.cost_entries(id uuid primary key default gen_random_uuid(),product_id uuid references catalog.products(id),order_id uuid references commerce.orders(id),category text not null,description text,amount numeric(18,2) not null,currency text not null default 'EGP',source_type text,source_id uuid,occurred_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists finance.product_costs(product_variant_id uuid primary key references catalog.product_variants(id) on delete cascade,material_cost numeric(18,2) not null default 0,labor_cost numeric(18,2) not null default 0,energy_cost numeric(18,2) not null default 0,packaging_cost numeric(18,2) not null default 0,shipping_allocation numeric(18,2) not null default 0,marketing_allocation numeric(18,2) not null default 0,payment_fee_allocation numeric(18,2) not null default 0,return_risk_allocation numeric(18,2) not null default 0,other_cost numeric(18,2) not null default 0,currency text not null default 'EGP',updated_at timestamptz not null default now());
create table if not exists finance.documents(id uuid primary key default gen_random_uuid(),document_type text not null,order_id uuid references commerce.orders(id),return_id uuid references logistics.returns(id),number text unique,language text not null default 'ar',status text not null default 'draft',storage_bucket text,storage_path text,snapshot jsonb not null default '{}',created_at timestamptz not null default now());

create table if not exists catalog.attributes(id uuid primary key default gen_random_uuid(),code text unique not null,name_ar text not null,name_en text,value_type text not null default 'text',options jsonb not null default '[]',created_at timestamptz not null default now());
create table if not exists catalog.product_type_attributes(product_type text not null,attribute_id uuid not null references catalog.attributes(id) on delete cascade,required boolean not null default false,sort_order integer not null default 0,primary key(product_type,attribute_id));
create table if not exists catalog.product_badges(id uuid primary key default gen_random_uuid(),product_id uuid references catalog.products(id) on delete cascade,variant_id uuid references catalog.product_variants(id) on delete cascade,code text not null,label_ar text not null,label_en text,status text not null default 'active',sort_order integer not null default 0,metadata jsonb not null default '{}');
create table if not exists catalog.product_relations(product_id uuid not null references catalog.products(id) on delete cascade,related_product_id uuid not null references catalog.products(id) on delete cascade,relation_type text not null,score numeric,sort_order integer not null default 0,primary key(product_id,related_product_id,relation_type));
create table if not exists catalog.search_synonyms(id uuid primary key default gen_random_uuid(),term text unique not null,synonyms text[] not null default '{}',language text not null default 'ar',status text not null default 'active');
create table if not exists catalog.seo_metadata(id uuid primary key default gen_random_uuid(),entity_type text not null,entity_id uuid not null,slug text,title_ar text,title_en text,description_ar text,description_en text,canonical_url text,robots text,og_image_path text,schema_json jsonb not null default '{}',unique(entity_type,entity_id));

create table if not exists growth.review_media(id uuid primary key default gen_random_uuid(),review_id uuid not null references growth.reviews(id) on delete cascade,bucket text not null,object_path text not null,media_type text not null,sort_order integer not null default 0);
create table if not exists growth.review_helpful(review_id uuid not null references growth.reviews(id) on delete cascade,customer_id uuid not null references customer.customers(id) on delete cascade,created_at timestamptz not null default now(),primary key(review_id,customer_id));
create table if not exists growth.review_responses(id uuid primary key default gen_random_uuid(),review_id uuid not null references growth.reviews(id) on delete cascade,actor_id uuid,body text not null,created_at timestamptz not null default now());
create table if not exists growth.membership_tiers(id uuid primary key default gen_random_uuid(),code text unique not null,name_ar text not null,name_en text,threshold_spend numeric(18,2) not null default 0,threshold_orders integer not null default 0,points_multiplier numeric(8,3) not null default 1,benefits jsonb not null default '{}',status text not null default 'active',sort_order integer not null default 0);
create table if not exists growth.customer_memberships(customer_id uuid primary key references customer.customers(id) on delete cascade,tier_id uuid references growth.membership_tiers(id),lifetime_spend numeric(18,2) not null default 0,order_count integer not null default 0,updated_at timestamptz not null default now());
create table if not exists growth.gift_orders(id uuid primary key default gen_random_uuid(),order_id uuid unique not null references commerce.orders(id) on delete cascade,recipient_name text not null,recipient_phone text,recipient_address jsonb not null default '{}',gift_message text,card_text text,packaging jsonb not null default '{}',requested_delivery_at timestamptz,status text not null default 'pending');
create table if not exists growth.subscriptions(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customer.customers(id),status text not null default 'draft',cadence text not null,items jsonb not null default '[]',next_order_at timestamptz,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists growth.preorders(id uuid primary key default gen_random_uuid(),product_variant_id uuid not null references catalog.product_variants(id),customer_id uuid not null references customer.customers(id),quantity numeric not null check(quantity>0),status text not null default 'reserved',expected_at timestamptz,order_id uuid references commerce.orders(id),created_at timestamptz not null default now());

create or replace function commerce.quote_checkout(p_currency text,p_location_id uuid,p_items jsonb,p_coupon_code text default null) returns jsonb language plpgsql security definer set search_path=commerce,customer,catalog,inventory,logistics,platform,public as $$
declare a uuid:=auth.uid();c uuid;x jsonb;v uuid;q numeric;pr record;sub numeric(18,2):=0;disc numeric(18,2):=0;ship numeric(18,2):=0;coupon commerce.coupons;rule logistics.shipping_rules;total numeric(18,2);items jsonb:='[]';
begin
if a is null then raise exception 'AUTH_REQUIRED';end if;select id into c from customer.customers where auth_user_id=a limit 1;if c is null then raise exception 'CUSTOMER_NOT_FOUND';end if;
if p_location_id is null then raise exception 'LOCATION_REQUIRED';end if;if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'EMPTY_CART';end if;
for x in select value from jsonb_array_elements(p_items) loop v:=(x->>'product_variant_id')::uuid;q:=(x->>'quantity')::numeric;if v is null or q is null or q<=0 then raise exception 'INVALID_CART_ITEM';end if;select * into pr from commerce.resolve_active_price(v,p_currency);if pr.price_id is null then raise exception 'PRICE_NOT_FOUND:%',v;end if;if coalesce((select sum(i.on_hand-i.reserved) from inventory.items i where i.product_variant_id=v),0)<q then raise exception 'OUT_OF_STOCK:%',v;end if;sub:=sub+round(pr.amount*q,2);items:=items||jsonb_build_array(jsonb_build_object('product_variant_id',v,'quantity',q,'unit_price',pr.amount));end loop;
if nullif(trim(coalesce(p_coupon_code,'')),'') is not null then select * into coupon from commerce.coupons where upper(code)=upper(trim(p_coupon_code)) and status='active' and (starts_at is null or starts_at<=now()) and (ends_at is null or ends_at>now()) for update;if not found then raise exception 'COUPON_INVALID';end if;if coupon.min_subtotal is not null and sub<coupon.min_subtotal then raise exception 'COUPON_MIN_SUBTOTAL';end if;if coupon.usage_limit is not null and (select count(*) from commerce.coupon_redemptions where coupon_id=coupon.id)>=coupon.usage_limit then raise exception 'COUPON_USAGE_LIMIT';end if;if coupon.discount_type='percent' then disc:=round(sub*coupon.discount_value/100,2);else disc:=coupon.discount_value;end if;if coupon.max_discount is not null then disc:=least(disc,coupon.max_discount);end if;disc:=least(disc,sub);end if;
select * into rule from logistics.shipping_rules where status='active' and (min_order is null or sub-disc>=min_order) and (max_order is null or sub-disc<=max_order) order by priority desc,created_at desc limit 1;if found then if rule.free_shipping_threshold is not null and sub-disc>=rule.free_shipping_threshold then ship:=0;else ship:=rule.price;end if;end if;total:=greatest(0,round(sub-disc+ship,2));
return jsonb_build_object('currency',p_currency,'location_id',p_location_id,'items',items,'subtotal',sub,'discount',disc,'shipping',ship,'tax',0,'grand_total',total);
end $$;
revoke all on function commerce.quote_checkout(text,uuid,jsonb,text) from public;grant execute on function commerce.quote_checkout(text,uuid,jsonb,text) to authenticated;
