-- Canonical replay of the live final-blueprint runtime migration.
create table if not exists customer.checkout_sessions(id uuid primary key default gen_random_uuid(),customer_id uuid references customer.customers(id) on delete cascade,session_key text unique not null,cart_snapshot jsonb not null default '[]',pricing_snapshot jsonb not null default '{}',shipping_snapshot jsonb not null default '{}',last_step text,failure_code text,status text not null default 'open',started_at timestamptz not null default now(),updated_at timestamptz not null default now(),recovered_order_id uuid references commerce.orders(id));
create table if not exists customer.buy_again_signals(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customer.customers(id) on delete cascade,product_variant_id uuid not null references catalog.product_variants(id),score numeric(10,4) not null default 0,estimated_repurchase_at timestamptz,last_ordered_at timestamptz,order_count integer not null default 0,metadata jsonb not null default '{}',updated_at timestamptz not null default now(),unique(customer_id,product_variant_id));
create table if not exists customer.referral_links(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customer.customers(id) on delete cascade,code text unique not null,landing_path text,clicks integer not null default 0,created_at timestamptz not null default now());
create table if not exists customer.preference_consents(customer_id uuid primary key references customer.customers(id) on delete cascade,marketing_email boolean not null default false,marketing_sms boolean not null default false,marketing_whatsapp boolean not null default false,analytics boolean not null default true,updated_at timestamptz not null default now());
create table if not exists analytics.kpis_daily(day date primary key,orders_count integer not null default 0,paid_orders_count integer not null default 0,gross_sales numeric(18,2) not null default 0,discounts numeric(18,2) not null default 0,shipping_revenue numeric(18,2) not null default 0,refunds numeric(18,2) not null default 0,estimated_cogs numeric(18,2) not null default 0,payment_cost numeric(18,2) not null default 0,contribution_profit numeric(18,2) not null default 0,currency text not null default 'EGP',refreshed_at timestamptz not null default now());
create table if not exists analytics.customer_metrics(customer_id uuid primary key references customer.customers(id) on delete cascade,order_count integer not null default 0,lifetime_revenue numeric(18,2) not null default 0,lifetime_profit numeric(18,2) not null default 0,average_order_value numeric(18,2) not null default 0,first_order_at timestamptz,last_order_at timestamptz,clv_estimate numeric(18,2) not null default 0,segment text,updated_at timestamptz not null default now());
create table if not exists analytics.product_metrics(product_variant_id uuid primary key references catalog.product_variants(id) on delete cascade,units_sold numeric(18,3) not null default 0,revenue numeric(18,2) not null default 0,gross_margin numeric(18,2) not null default 0,return_rate numeric(10,4) not null default 0,stock_turnover numeric(10,4) not null default 0,updated_at timestamptz not null default now());
create table if not exists platform.webhook_deliveries(id uuid primary key default gen_random_uuid(),event_id uuid references platform.system_events(id),endpoint text not null,provider text,status text not null default 'queued',attempt_count integer not null default 0,next_attempt_at timestamptz,response_code integer,response_body text,idempotency_key text unique,created_at timestamptz not null default now(),delivered_at timestamptz);
create table if not exists platform.ai_tool_permissions(tool_code text primary key,enabled boolean not null default false,risk_level text not null default 'low',read_only boolean not null default true,allowed_roles text[] not null default '{}',description text);
create table if not exists platform.api_keys(id uuid primary key default gen_random_uuid(),name text not null,key_prefix text not null unique,key_hash text not null unique,status text not null default 'active',scopes text[] not null default '{}',expires_at timestamptz,last_used_at timestamptz,created_at timestamptz not null default now());
alter table customer.checkout_sessions enable row level security;alter table customer.buy_again_signals enable row level security;alter table customer.preference_consents enable row level security;alter table customer.referral_links enable row level security;